import type { Tool, Workflow, AuditLog } from '../types';

export const INITIAL_REGISTERED_TOOLS: Tool[] = [
  {
    id: 'tool-search-1',
    name: 'search_information',
    description: 'Queries internal data stores and logs to gather context for requested operations.',
    input_schema: { query: 'string' },
    requires_approval: false,
    risk_level: 'LOW',
    status: 'ACTIVE',
  },
  {
    id: 'tool-update-2',
    name: 'update_record',
    description: 'Modifies user profile records, payment configurations, or permission boundaries.',
    input_schema: { table: 'string', record_id: 'string', values: 'object' },
    requires_approval: true,
    risk_level: 'HIGH',
    status: 'ACTIVE',
  },
  {
    id: 'tool-notify-3',
    name: 'send_notification',
    description: 'Sends email or SMS alerts to relevant team members regarding workflow completion.',
    input_schema: { recipient: 'string', message: 'string' },
    requires_approval: false,
    risk_level: 'LOW',
    status: 'ACTIVE',
  },
];

export const INITIAL_SAMPLE_WORKFLOWS: Workflow[] = [
  {
    id: 'wf-sample-1',
    user_id: '11111111-1111-4111-8111-111111111111',
    goal: 'Audit and update user access permissions for security compliance',
    status: 'COMPLETED',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    steps: [
      {
        id: 'step-1',
        workflow_id: 'wf-sample-1',
        tool_id: 'tool-search-1',
        tool_name: 'search_information',
        step_order: 1,
        arguments: { query: 'active user permissions' },
        output: { count: 42, audited: true },
        status: 'COMPLETED',
        retry_count: 0,
        requires_approval: false,
      },
      {
        id: 'step-2',
        workflow_id: 'wf-sample-1',
        tool_id: 'tool-update-2',
        tool_name: 'update_record',
        step_order: 2,
        arguments: { table: 'permissions', record_id: 'sec-884' },
        output: { updated: true, policy: 'enforced' },
        status: 'COMPLETED',
        retry_count: 0,
        requires_approval: true,
      },
      {
        id: 'step-3',
        workflow_id: 'wf-sample-1',
        tool_id: 'tool-notify-3',
        tool_name: 'send_notification',
        step_order: 3,
        arguments: { recipient: 'security@corex.ai', message: 'Audit completed' },
        output: { dispatched: true },
        status: 'COMPLETED',
        retry_count: 0,
        requires_approval: false,
      },
    ],
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    workflow_id: 'wf-sample-1',
    step_id: null,
    actor: 'Control Gate',
    action: 'WORKFLOW_CREATED',
    details: { goal: 'Audit and update user access permissions for security compliance' },
    result: 'INFO',
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'log-2',
    workflow_id: 'wf-sample-1',
    step_id: 'step-1',
    actor: 'Tool Executor',
    action: 'TOOL_EXECUTED',
    details: { tool_name: 'search_information', output: { count: 42, audited: true } },
    result: 'SUCCESS',
    created_at: new Date(Date.now() - 3500000).toISOString(),
  },
  {
    id: 'log-3',
    workflow_id: 'wf-sample-1',
    step_id: 'step-2',
    actor: 'Control Gate',
    action: 'APPROVAL_REQUESTED',
    details: { tool_name: 'update_record', risk_level: 'HIGH' },
    result: 'INFO',
    created_at: new Date(Date.now() - 3400000).toISOString(),
  },
  {
    id: 'log-4',
    workflow_id: 'wf-sample-1',
    step_id: 'step-2',
    actor: 'User (Human Approver)',
    action: 'HUMAN_APPROVED',
    details: { decision: 'APPROVED' },
    result: 'SUCCESS',
    created_at: new Date(Date.now() - 3300000).toISOString(),
  },
  {
    id: 'log-5',
    workflow_id: 'wf-sample-1',
    step_id: 'step-2',
    actor: 'Tool Executor',
    action: 'TOOL_EXECUTED',
    details: { tool_name: 'update_record', output: { updated: true } },
    result: 'SUCCESS',
    created_at: new Date(Date.now() - 3200000).toISOString(),
  },
  {
    id: 'log-6',
    workflow_id: 'wf-sample-1',
    step_id: 'step-3',
    actor: 'Tool Executor',
    action: 'TOOL_EXECUTED',
    details: { tool_name: 'send_notification', output: { dispatched: true } },
    result: 'SUCCESS',
    created_at: new Date(Date.now() - 3100000).toISOString(),
  },
  {
    id: 'log-7',
    workflow_id: 'wf-sample-1',
    step_id: null,
    actor: 'Control Gate',
    action: 'WORKFLOW_COMPLETED',
    details: { workflow_id: 'wf-sample-1', status: 'COMPLETED' },
    result: 'SUCCESS',
    created_at: new Date(Date.now() - 3000000).toISOString(),
  },
];
